#!/bin/bash
# Generated by clean_unrelated.py
# Target Directory: /home/the100rabh/code/personal/100rabhs-website.github.io
# Number of files to delete: 83

set -euo pipefail

# Store target directory and files to delete
BASE_DIR="/home/the100rabh/code/personal/100rabhs-website.github.io"

FILES_TO_DELETE=(
    "CNAME"
    "css/bootstrap.min.css"
    "css/fontAwesome.css"
    "css/fonts/flexslider-icon.eot"
    "css/fonts/flexslider-icon.svg"
    "css/fonts/flexslider-icon.ttf"
    "css/fonts/flexslider-icon.woff"
    "css/hero-slider.css"
    "css/main.css"
    "css/owl-carousel.css"
    "fontawesome/css/all.min.css"
    "fontawesome/css/brands.css"
    "fontawesome/css/brands.min.css"
    "fontawesome/css/fontawesome.css"
    "fontawesome/css/fontawesome.min.css"
    "fontawesome/css/regular.css"
    "fontawesome/css/regular.min.css"
    "fontawesome/css/solid.css"
    "fontawesome/css/solid.min.css"
    "fontawesome/css/svg-with-js.css"
    "fontawesome/css/svg-with-js.min.css"
    "fontawesome/css/v4-font-face.css"
    "fontawesome/css/v4-font-face.min.css"
    "fontawesome/css/v4-shims.min.css"
    "fontawesome/css/v5-font-face.css"
    "fontawesome/css/v5-font-face.min.css"
    "fonts/FontAwesome.otf"
    "fonts/fontawesome-webfont.eot"
    "fonts/fontawesome-webfont.svg"
    "fonts/fontawesome-webfont.ttf"
    "fonts/fontawesome-webfont.woff"
    "fonts/fontawesome-webfont.woff2"
    "fonts/glyphicons-halflings-regular.eot"
    "fonts/glyphicons-halflings-regular.svg"
    "fonts/glyphicons-halflings-regular.ttf"
    "fonts/glyphicons-halflings-regular.woff"
    "github-widget/github-widget.coffee"
    "github-widget/github-widget.js"
    "github-widget/github-widget.min.js"
    "img/1st-big-item.jpg"
    "img/1st-item.jpg"
    "img/1st-section.jpg"
    "img/1st-section_laptop.jpg"
    "img/1st-tab.jpg"
    "img/2nd-big-item.jpg"
    "img/2nd-item.jpg"
    "img/2nd-section-linux.jpg"
    "img/2nd-section.jpg"
    "img/2nd-tab.jpg"
    "img/3rd-big-item.jpg"
    "img/3rd-item.jpg"
    "img/3rd-section-mobile.jpg"
    "img/3rd-section-social-org.jpg"
    "img/3rd-section-social.jpg"
    "img/3rd-section.jpg"
    "img/3rd-tab.jpg"
    "img/4th-big-item.jpg"
    "img/4th-item.jpg"
    "img/4th-section.jpg"
    "img/4th-tab.jpg"
    "img/5th-big-item.jpg"
    "img/5th-item.jpg"
    "img/5th-section.jpg"
    "img/6th-big-item.jpg"
    "img/6th-item.jpg"
    "img/Bengaluru_logo-650x500.jpeg"
    "img/Bengaluru_logo-650x500.png"
    "img/avatar.png"
    "img/avatar2.png"
    "img/bengaluru.svg"
    "img/close.png"
    "img/loading.gif"
    "img/next.png"
    "img/prev.png"
    "js/app.js"
    "js/main.js"
    "js/plugins.js"
    "js/test-module.js"
    "js/vendor/bootstrap.min.js"
    "js/vendor/jquery-1.11.2.min.js"
    "js/vendor/modernizr-2.8.3-respond-1.4.2.min.js"
    "js/vendor/npm.js"
    "mastodon.widget-jp.js"
)

TOTAL_FILES=${#FILES_TO_DELETE[@]}

if [ "$TOTAL_FILES" -eq 0 ]; then
    echo "No unrelated files to delete."
    exit 0
fi

DRY_RUN=false

# Parse command line options
for arg in "$@"; do
    case $arg in
        -d|--dry-run)
            DRY_RUN=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [options]"
            echo "Options:"
            echo "  -d, --dry-run    Only show files that would be deleted, do not delete them"
            echo "  -h, --help       Show this help message"
            exit 0
            ;;
    esac
done

if [ "$DRY_RUN" = true ]; then
    echo "=== DRY RUN: The following $TOTAL_FILES files would be deleted ==="
    for file in "${FILES_TO_DELETE[@]}"; do
        echo "  [DRY-RUN] $file"
    done
    exit 0
fi

echo "The following $TOTAL_FILES files are unrelated and will be DELETED:"
for file in "${FILES_TO_DELETE[@]}"; do
    echo "  $file"
done

echo ""
read -p "Are you sure you want to permanently delete these $TOTAL_FILES files? (y/N): " confirm

if [[ "$confirm" =~ ^[Yy](es)?$ ]]; then
    echo "Deleting files..."
    for file in "${FILES_TO_DELETE[@]}"; do
        full_path="$BASE_DIR/$file"
        if [ -f "$full_path" ]; then
            rm "$full_path"
            echo "  Deleted: $file"
        elif [ -d "$full_path" ]; then
            rm -rf "$full_path"
            echo "  Deleted directory: $file"
        else
            echo "  Not found: $file"
        fi
    done
    
    # Clean up empty subdirectories
    echo "Cleaning up empty directories..."
    find "$BASE_DIR" -type d -empty -delete 2>/dev/null || true
    echo "Done!"
else
    echo "Deletion cancelled."
fi
